import "./globals.css";
import React from 'react';

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen dark:bg-gray-900">
        {children}
      </body>
    </html>
  );
}
